### PR TITLE
update mono version

### PR DESCRIPTION
**Pull request by juicelink**

### CODE REVIEW

**Comment by haf** [comment]
@juicelink Thanks!

**Comment by haf** [comment]
Have you tested it?

Could you also PR updated git-hashes to this file? https://github.com/docker-library/official-images/blob/master/library/fsharp

**Comment by juicelink** [comment]
tested the 4.0.1.1 one

**Comment by juicelink** [comment]
ok for the PR

**Comment by haf** [comment]
Thanks!

**Comment by juicelink** [comment]
tested 4.0.0.4 seems ok too

**Pull request merged**
