### PR TITLE
Update maintainer details on docker image repo

### PR DESCRIPTION
**Pull request by dsyme**
@haf - You mentioned you would prefer not to be responsible for distribution/packaging - does that include the docker image?  If so we'll work out a maintainer for this. Thanks :)

### CODE REVIEW

**Comment by haf** [comment]
I'm happy to help review but I'd prefer if someone took the lead on this repo. Thank you Don.

**Comment by SteveDesmond-ca** [comment]
I'd be glad to step up, but also happy to let another volunteer have the privilege :)

While not super well-versed in F# specifically, I'm all about build automation and containers these days.

**Comment by dsyme** [comment]
@stevedesmond-ca Thanks for the offer!!  May we ask - do you have any Mono and/or .NET Core-on-Linux experience?  That's the main thing I suppose.  I guess it would also be useful to have someone who is actively using the containers being produced here.

If I understand correctly the main job is to update the selection of containers available to include 
* updated versions of Mono 
* updated versions of F#
* options for a base image that has .NET Core installed rather than Mono (@enricosada may be able to help there)

Also comparing with other languages to see the kind of flavours they offer may be useful. 

(Note: There might also be Mono + F# containers already available. Mono often comes with F# (e.g. on OSX that's always the case) so sometimes Mono images can act as F# images.  )

**Comment by dsyme** [comment]
@neoeinstein has also offered, see https://twitter.com/neoeinstein/status/854812240633049088, perhaps with a focus on ,.NET Core

Note that https://github.com/fsprojects/docker-fsharp/issues/3 is an issue to add a "-core" tag for .NET Core.  It needs to be completed though

**Comment by dsyme** [comment]
BTW I would also love to see docker containers for FsLab http://fslab.org, and I think some cooperation with the Suave containers would also be useful

**Comment by SteveDesmond-ca** [comment]
I agree, a more active F# user would be best, but I'm good assuming the mantle otherwise. Pretty much all of my .NET Core work is on Linux, and most of my ASP.NET Core apps (e.g. https://stevedesmond.ca) are running via Docker on Linux. Mono I'm a little lighter on, mostly just when things like Cake needed it, and pre-.NET Core.

**Comment by haf** [comment]
+1 for @stevedesmond-ca or @ninjarobot or a both of them. 

@ninjarobot In my opinion: 

 - SDK for builds (highest prio) and another mono container for builds (highest prio),
 - a container for deployments on mono (high prio) and another container for on core (high prio), and
 - the CI toolchain (lowest prio) would be great.

**Comment by dsyme** [comment]
@stevedesmond-ca @ninjarobot OK, I've added you both. Welcome aboard!

I'll step back from active participation but will try to use the containers.  Please keep an eye on tags in http://github.com/fsharp/fsharp and update any information/links in the README.md there

**Comment by dsyme** [comment]
Correct - thanks!

**Pull request closed without merging**
